language: php

matrix:
    include:
        - 5.4
        - 5.5
        - 5.6
        - nightly
        - hhvm
        - hhvm-nightly
    allow_failures:
        - nightly
        - php: hhvm-nightly
    fast_finish: true

before_script:
    - composer install --prefer-source

script: phpunit --bootstrap vendor/autoload.php tests

notifications:
  email: false
